"""

------------------------------------- Link for the challenge: https://codeforces.com/problemset/problem/1278/A ---------------------------

Polycarp has built his own web service. Being a modern web service it includes login feature. And that always implies password security problems.

Polycarp decided to store the hash of the password, generated by the following algorithm:

take the password p, consisting of lowercase Latin letters, and shuffle the letters randomly in it to obtain p′ (p′ can still be equal to p);
generate two random strings, consisting of lowercase Latin letters, s1 and s2 (any of these strings can be empty);
the resulting hash h=s1+p′+s2, where addition is string concatenation.
For example, let the password p= "abacaba". 
Then p′ can be equal to "aabcaab". Random strings s1= "zyx" and s2= "kjh". Then h= "zyxaabcaabkjh".

Note that no letters could be deleted or added to p to obtain p′, only the order could be changed.

Now Polycarp asks you to help him to implement the password check module. Given the password p and the hash h, check that h can be the hash for the password p.

Your program should answer t independent test cases.

Input
The first line contains one integer t (1 ≤ t ≤ 100) — the number of test cases.

The first line of each test case contains a non-empty string p, consisting of lowercase Latin letters. The length of p does not exceed 100.

The second line of each test case contains a non-empty string h, consisting of lowercase Latin letters. The length of h does not exceed 100.

Output
For each test case print the answer to it — "YES" if the given hash h could be obtained from the given password p or "NO" otherwise.

Input:
5
abacaba
zyxaabcaabkjh
onetwothree
threetwoone
one
zzonneyy
one
none
twenty
ten

Output:
YES
YES
NO
YES
NO
"""
from collections import Counter

cases = int(input())
for _ in range(cases):
    p = input()
    h = input()
    target_counts = Counter(p)

    p_sze = len(p)
    h_sze = len(h)
    if(p_sze > h_sze):
        print("NO")
        continue

    window_counts = Counter(h[:p_sze])
    if(window_counts == target_counts):
        print("YES")
        continue

    ok = False
    for i in range(1, h_sze - p_sze + 1):
        char_to_remove = h[i - 1]
        char_to_add = h[i + p_sze - 1]

        window_counts[char_to_remove] -= 1
        window_counts[char_to_add] += 1

        if(window_counts[char_to_remove] == 0):
            del window_counts[char_to_remove]

        if(window_counts == target_counts):
            ok = True
            break
    print("YES" if ok else "NO")
